# Generated by Django 3.0.7 on 2020-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('urlBase', models.CharField(max_length=200, verbose_name='urlBase')),
                ('OBdata', models.CharField(max_length=50, verbose_name='OBdata')),
                ('OBrelevancia', models.CharField(max_length=50, verbose_name='OBrelevancia')),
            ],
        ),
    ]
